### PR TITLE
Expose internal modules; fixes #359, #235

### LINKED ISSUE #359: I can't define a Numeric instance for a newtype of Double (Internal modules need to be exposed)
I'm stuck here (internal module, so I can't reach the type and tell it to just use Double for C calls, etc.):

```
src/HordeAd/Core/HasDual.hs:353:1: error:
    • Could not deduce (hmatrix-0.20.2:Internal.Numeric.CTrans
                          (Forward a))
        arising from the superclasses of an instance declaration
      from the context: (HM.Product (Forward a), HM.Container Vector a)
        bound by the instance declaration
        at src/HordeAd/Core/HasDual.hs:(353,1)-(354,43)
    • In the instance declaration for ‘Numeric (Forward a)’
    |
353 | deriving instance (HM.Product (Forward a), HM.Container Vector a)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

BTW, deriving with GHC 9.2.2

```
deriving instance (HM.Element a, Ord a) => HM.Element (Forward a)

deriving instance (HM.Container Vector a, Ord a, Integral a, Fractional a)
                  => HM.Container Vector (Forward a)
```

produces the following warnings:

```
src/HordeAd/Core/HasDual.hs:346:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Ord (Forward a)
    • In the type signature for:
           hmatrix-0.20.2:Internal.Matrix.sortI :: Ord (Forward a) =>
                                                   Vector (Forward a) -> Vector Foreign.C.Types.CInt
      When typechecking the code for ‘hmatrix-0.20.2:Internal.Matrix.sortI’
        in a derived instance for ‘HM.Element (Forward a)’:
        To see the code I am typechecking, use -ddump-deriv
      In the instance declaration for ‘HM.Element (Forward a)’
    |
346 | deriving instance (HM.Element a, Ord a) => HM.Element (Forward a)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/HordeAd/Core/HasDual.hs:346:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Ord (Forward a)
    • In the type signature for:
           hmatrix-0.20.2:Internal.Matrix.sortV :: Ord (Forward a) =>
                                                   Vector (Forward a) -> Vector (Forward a)
      When typechecking the code for ‘hmatrix-0.20.2:Internal.Matrix.sortV’
        in a derived instance for ‘HM.Element (Forward a)’:
        To see the code I am typechecking, use -ddump-deriv
      In the instance declaration for ‘HM.Element (Forward a)’
    |
346 | deriving instance (HM.Element a, Ord a) => HM.Element (Forward a)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/HordeAd/Core/HasDual.hs:346:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Ord (Forward a)
    • In the type signature for:
           hmatrix-0.20.2:Internal.Matrix.compareV :: Ord (Forward a) =>
                                                      Vector (Forward a)
                                                      -> Vector (Forward a)
                                                      -> Vector Foreign.C.Types.CInt
      When typechecking the code for ‘hmatrix-0.20.2:Internal.Matrix.compareV’
        in a derived instance for ‘HM.Element (Forward a)’:
        To see the code I am typechecking, use -ddump-deriv
      In the instance declaration for ‘HM.Element (Forward a)’
    |
346 | deriving instance (HM.Element a, Ord a) => HM.Element (Forward a)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/HordeAd/Core/HasDual.hs:348:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Ord (Forward a)
    • In the type signature for:
           hmatrix-0.20.2:Internal.Numeric.step' :: Ord (Forward a) =>
                                                    Vector (Forward a) -> Vector (Forward a)
      When typechecking the code for ‘hmatrix-0.20.2:Internal.Numeric.step'’
        in a derived instance for ‘HM.Container Vector (Forward a)’:
        To see the code I am typechecking, use -ddump-deriv
      In the instance declaration for ‘HM.Container Vector (Forward a)’
    |
348 | deriving instance (HM.Container Vector a, Ord a, Integral a, Fractional a)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/HordeAd/Core/HasDual.hs:348:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Ord (Forward a)
    • In the type signature for:
           hmatrix-0.20.2:Internal.Numeric.ccompare' :: Ord (Forward a) =>
                                                        Vector (Forward a)
                                                        -> Vector (Forward a) -> Vector HM.I
      When typechecking the code for ‘hmatrix-0.20.2:Internal.Numeric.ccompare'’
        in a derived instance for ‘HM.Container Vector (Forward a)’:
        To see the code I am typechecking, use -ddump-deriv
      In the instance declaration for ‘HM.Container Vector (Forward a)’
    |
348 | deriving instance (HM.Container Vector a, Ord a, Integral a, Fractional a)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/HordeAd/Core/HasDual.hs:348:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Fractional (Forward a)
    • In the type signature for:
           hmatrix-0.20.2:Internal.Numeric.scaleRecip :: Fractional
                                                           (Forward a) =>
                                                         Forward a
                                                         -> Vector (Forward a) -> Vector (Forward a)
      When typechecking the code for ‘hmatrix-0.20.2:Internal.Numeric.scaleRecip’
        in a derived instance for ‘HM.Container Vector (Forward a)’:
        To see the code I am typechecking, use -ddump-deriv
      In the instance declaration for ‘HM.Container Vector (Forward a)’
    |
348 | deriving instance (HM.Container Vector a, Ord a, Integral a, Fractional a)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/HordeAd/Core/HasDual.hs:348:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Fractional (Forward a)
    • In the type signature for:
           hmatrix-0.20.2:Internal.Numeric.divide :: Fractional (Forward a) =>
                                                     Vector (Forward a)
                                                     -> Vector (Forward a) -> Vector (Forward a)
      When typechecking the code for ‘hmatrix-0.20.2:Internal.Numeric.divide’
        in a derived instance for ‘HM.Container Vector (Forward a)’:
        To see the code I am typechecking, use -ddump-deriv
      In the instance declaration for ‘HM.Container Vector (Forward a)’
    |
348 | deriving instance (HM.Container Vector a, Ord a, Integral a, Fractional a)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/HordeAd/Core/HasDual.hs:348:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Fractional (Forward a)
    • In the type signature for:
           hmatrix-0.20.2:Internal.Numeric.arctan2' :: Fractional
                                                         (Forward a) =>
                                                       Vector (Forward a)
                                                       -> Vector (Forward a) -> Vector (Forward a)
      When typechecking the code for ‘hmatrix-0.20.2:Internal.Numeric.arctan2'’
        in a derived instance for ‘HM.Container Vector (Forward a)’:
        To see the code I am typechecking, use -ddump-deriv
      In the instance declaration for ‘HM.Container Vector (Forward a)’
    |
348 | deriving instance (HM.Container Vector a, Ord a, Integral a, Fractional a)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/HordeAd/Core/HasDual.hs:348:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Integral (Forward a)
    • In the type signature for:
           hmatrix-0.20.2:Internal.Numeric.cmod' :: Integral (Forward a) =>
                                                    Forward a
                                                    -> Vector (Forward a) -> Vector (Forward a)
      When typechecking the code for ‘hmatrix-0.20.2:Internal.Numeric.cmod'’
        in a derived instance for ‘HM.Container Vector (Forward a)’:
        To see the code I am typechecking, use -ddump-deriv
      In the instance declaration for ‘HM.Container Vector (Forward a)’
    |
348 | deriving instance (HM.Container Vector a, Ord a, Integral a, Fractional a)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

### PR DESCRIPTION
**Pull request by Mikolaj**
Here are instances of hmatrix classes for a newtype of Double made possible by this PR:  https://github.com/Mikolaj/horde-ad/blob/01f5b467d1b0ccf9e8e4244e0837829f857a6807/src/HordeAd/Internal/HmatrixOrphanInstances.hs

They are tested and work fine. Making derivation of the instances easier and less susceptible to breakage when hmatrix changes would be very welcome, but just exposing internal modules is enough for me and I won't need to make a fork (which would be a horror to maintain, I'm sure).

### CODE REVIEW

**Comment by Mikolaj** [comment]
Gentle ping? This is a minimal change and it would help a lot.

**Review by idontgetoutmuch — APPROVED** [review]

**Comment by idontgetoutmuch** [comment]
I wasn't aware of your library - looks pretty cool - I will try it out for a project I have ongoing where I just resorted to my own forward mode implementation (I couldn't get the types to work with ad and backdrop.

Did you want me to make a release on hackage?

**Comment by Mikolaj** [comment]
> Did you want me to make a release on hackage?

Thank you so much for merging. No rush; I've made do with some C hacks for now (and worked around in yet another way a year ago to stop maintaining a fork). I will yell once again when I need the internals on Hackage. 

> I wasn't aware of your library - looks pretty cool - I will try it out for a project I have ongoing where I just resorted to my own forward mode implementation (I couldn't get the types to work with ad and backdrop).

You are very welcome and please let me know how it goes and ask questions (perhaps even open a joint ticket in horde-ad repo for all your questions and requests you may have and to think aloud as you progress). It's a big bunch of WIP, but the exposed API is old enough and probably stable and performant enough, so this may work fine. Make sure to choose the flavour with strict type-level shape checking or one of the less typed ones, depending on your use case. There's quite a lot of flexibility there (and little documentation so far, so please ask).

**Comment by HuwCampbell** [comment]
Hi hi.

Before publishing, I would very strongly suggest changing the module hierarchy

Exposing:
```
Internal.Devel
```
is really not a great idea. If internal modules are to be exposed, it should be as
```
Numeric.LinearAlgebra.Internal.Devel
```

**Pull request merged**
